core:
  ri: 27.0e-3  # inner radius
  ro: 42.0e-3  # outer radius
  h: 12.7e-3  # core height
  Al: 2726e-9  # [H/T^2]  # inductance factor
  N_cores: 2  # number of cores stacked in axial direction
secondary:
  tube_d: 12.7e-3  # copper tube OD
  tube_t: 0.7e-3  # copper tube thickness
primary:
  bobbin_dr: 1.0e-3  # radial thickness of the bobbin
  wire_d: 3.0e-3  # diameter of the wire
  litz_strands: 100  # number of strands in litz wire per conductor
  N: 10  # number of turns
